export default {
	defaultFields: [ 'id' ],
	fields: {
		'id': 'f',
		'org': 'f',
		'name': 'fs',
		'mayVote': 'f',
		'hasVoted': 'f',
		'hasResults': 'f',
		'percentageVoted': '',
		'description': 's',
		'timeStart': 'f',
		'timeEnd': 'f',
		'usedTieBreaker': '',
		'hasStarted': 'f',
		'hasEnded': 'f',
		'isActive': 'f',
		'isTieBreaker': '',
		'ballotsSecret': '',
		'type': 'f',
		'blankBallotsLimit': '',
		'blankBallotsLimitInclusive': '',
		'quorum': '',
		'quorumInclusive': '',
		'majorityBallots': '',
		'majorityBallotsInclusive': '',
		'majorityVoters': '',
		'majorityVotersInclusive': '',
		'majorityMustReachBoth': '',
		'numChosenOptions': '',
		'mentionThreshold': '',
		'mentionThresholdInclusive': '',
		'maxOptionsPerBallot': '',
		'tieBreakerCodeholder': '',
		'publishResults': '',
		'publishVoters': '',
		'publishVotersPercentage': '',
		'options': ''
	},
	fieldAliases: {
		percentageVoted: () => AKSO.db.raw('IF(publishVotersPercentage,(SELECT COUNT(1) FROM votes_ballots WHERE voteId = id) / (SELECT COUNT(1) FROM votes_voters WHERE mayVote AND voteId = id),NULL)'),
		hasVoted: () => AKSO.db.raw('timeVoted IS NOT NULL'),
		hasStarted: () => AKSO.db.raw('timeStart <= UNIX_TIMESTAMP()'),
		hasEnded: () => AKSO.db.raw('timeEnd <= UNIX_TIMESTAMP()'),
		isActive: () => AKSO.db.raw('timeStart <= UNIX_TIMESTAMP() AND timeEnd > UNIX_TIMESTAMP()'),
		isTieBreaker: () => AKSO.db.raw('results->"$.result" = "TIE_BREAKER_NEEDED" AND tieBreakerCodeholder = codeholderId',),
		usedTieBreaker: () => AKSO.db.raw('tieBreakerBallot IS NOT NULL')
	}
};
